Repository dydxprotocol/protocol, pull requests merged in 2018-06, with the labels that each got.

#358 Add missing field to VerifyLoanOffering()
  contracts/margin/impl/BorrowShared.sol
  contracts/margin/interfaces/LoanOfferingVerifier.sol
  contracts/testing/TestSmartContractLender.sol
Labels: bug

#361 Upgrade to zeppelin-solidity 1.10.0
  package-lock.json
  package.json
Labels: task

#360 Let smart-contract lenders verify their own signature data
  contracts/margin/Margin.sol
  contracts/margin/impl/BorrowShared.sol
  contracts/margin/impl/IncreasePositionImpl.sol
  contracts/margin/impl/LoanGetters.sol
  contracts/margin/impl/LoanImpl.sol
  contracts/margin/impl/MarginCommon.sol
  contracts/margin/impl/MarginEvents.sol
  contracts/margin/impl/MarginState.sol
  contracts/margin/impl/OpenPositionImpl.sol
  contracts/margin/interfaces/LoanOfferingVerifier.sol
  contracts/testing/TestSmartContractLender.sol
  test/helpers/Constants.js
  test/helpers/LoanHelper.js
  test/helpers/MarginHelper.js
  test/margin/TestApproveLoan.js
  test/margin/TestInvalidPositions.js
  test/margin/TestLoanGetters.js
  test/margin/TestMarginAdmin.js
  test/margin/TestOpenPosition.js
  test/margin/external/TestERC721MarginLoan.js
  util/lintcontracts.py
Labels: Code Clarity, P1, enhancement
