Repository dydxprotocol/protocol, pull requests merged in 2018-07, with the labels that each got.

#373 Upgrade Dependencies
  .soliumrc.json
  contracts/margin/external/ERC721/ERC721MarginLoan.sol
  contracts/margin/external/ERC721/ERC721MarginPosition.sol
  contracts/margin/external/SharedLoan.sol
  package-lock.json
  package.json
Labels: enhancement, task

#380 Fix Docker Build
  package-lock.json
  package.json
  scripts/docker.sh
Labels: bug

#384 add multiple signature types
  contracts/lib/TypedSignature.sol
  contracts/margin/impl/BorrowShared.sol
  contracts/testing/TestTypedSignature.sol
  test/helpers/Constants.js
  test/helpers/LoanHelper.js
  test/lib/TestTypedSignature.js
Labels: Requires Client Changes, enhancement

#386 0.1.5
  migrations/deployments.md
  package-lock.json
  package.json
  src/index.js
  truffle.js
Labels: task
