Repository dydxprotocol/protocol, pull requests merged in 2018-08, with the labels that each got.

#391 Add Snapshotting + Test Positions on Docker + Auto Publish
  .babelrc
  .circleci/config.yml
  Dockerfile
  migrations/1_initial_migration.js
  migrations/2_deploy.js
  migrations/3_docker.js
  migrations/deployed.json
  package-lock.json
  package.json
  scripts/clean-build.js
  scripts/docker.sh
  scripts/prod_build.sh
  scripts/publish_if_not_exists.sh
  scripts/save-deployed-addresses.js
  src/contracts.js
  src/index.js
  src/testing.js
  test/helpers/MarginHelper.js
  test/helpers/SnapshotHelper.js
Labels: Code Clarity, Requires Client Changes, task

#390 Change contracts to interfaces
  contracts/margin/external/interfaces/PositionCustodian.sol
  contracts/margin/interfaces/LoanOfferingVerifier.sol
  contracts/margin/interfaces/PayoutRecipient.sol
  contracts/margin/interfaces/lender/CancelMarginCallDelegator.sol
  contracts/margin/interfaces/lender/CloseLoanDelegator.sol
  contracts/margin/interfaces/lender/ForceRecoverCollateralDelegator.sol
  contracts/margin/interfaces/lender/IncreaseLoanDelegator.sol
  contracts/margin/interfaces/lender/LoanOwner.sol
  contracts/margin/interfaces/lender/MarginCallDelegator.sol
  contracts/margin/interfaces/owner/ClosePositionDelegator.sol
  contracts/margin/interfaces/owner/DepositCollateralDelegator.sol
  contracts/margin/interfaces/owner/IncreasePositionDelegator.sol
  contracts/margin/interfaces/owner/PositionOwner.sol
Labels: Code Clarity

#392 Misspell /build/test-posiitions => /build/test-positions
  package-lock.json
  package.json
  src/testing.js
Labels: bug

#397 Fix package dependencies
  package-lock.json
  package.json
Labels: bug, js

#398 0.2.0
  .circleci/config.yml
  README.md
  migrations/3_positions.js
  migrations/deployed.json
  package-lock.json
  package.json
  src/contracts.js
  src/index.js
  src/seeds.js
  src/snapshots.js
  src/test-positions.js
  test/helpers/ZeroExHelper.js
  test/tests/js/TestTesting.js
Labels: Code Clarity, js, task, tests

#400 Fix docker build
  Dockerfile
  package-lock.json
  package.json
  scripts/docker.sh
  scripts/prod_build.sh
  scripts/publish_if_not_exists.sh
Labels: bug

#401 Publish to es5
  .babelrc
  migrations/3_seeds.js
  package-lock.json
  package.json
  scripts/clean-build.js
  scripts/save-deployed-addresses.js
  src/contracts.js
  src/index.js
  src/lib/contracts.js
  src/lib/seeds.js
  src/lib/snapshots.js
Labels: bug, js

#411 Deploy short tokens with bucket lender
  migrations/3_seeds.js
  package-lock.json
  package.json
  src/lib/contracts.js
  test/helpers/ERC20PositionHelper.js
  test/helpers/MarginHelper.js
Labels: js, task

#414 Add seed orders for WETH
  migrations/3_seeds.js
  package-lock.json
  package.json
  test/helpers/ERC20PositionHelper.js
  test/helpers/ZeroExHelper.js
Labels: js

#417 Use provider when snapshotting
  README.md
  migrations/3_seeds.js
  package-lock.json
  package.json
  src/lib/snapshots.js
  test/tests/js/TestReset.js
  test/tests/js/TestSeeds.js
Labels: js

#418 fix publish script
  scripts/publish_if_not_exists.sh
Labels: bug, js

#419 Upgrade + Fix Build Script
  package-lock.json
  package.json
  scripts/clean-build.js
  scripts/prod_build.sh
  test/helpers/ERC20PositionHelper.js
Labels: bug, js, task

#420 Fix reset / snapshot
  README.md
  package-lock.json
  package.json
  src/lib/snapshots.js
Labels: bug, js

#421 zeppelin-solidity -> openzeppelin-solidity
  .solcover.js
  contracts/lib/Exponent.sol
  contracts/lib/FractionMath.sol
  contracts/lib/MathHelpers.sol
  contracts/lib/StaticAccessControlled.sol
  contracts/margin/Margin.sol
  contracts/margin/TokenProxy.sol
  contracts/margin/Vault.sol
  contracts/margin/external/BucketLender/BucketLender.sol
  contracts/margin/external/BucketLender/BucketLenderFactory.sol
  contracts/margin/external/ERC20/ERC20CappedLong.sol
  contracts/margin/external/ERC20/ERC20CappedShort.sol
  contracts/margin/external/ERC20/ERC20Long.sol
  contracts/margin/external/ERC20/ERC20Position.sol
  contracts/margin/external/ERC20/ERC20PositionFactory.sol
  contracts/margin/external/ERC20/ERC20Short.sol
  contracts/margin/external/ERC721/ERC721MarginLoan.sol
  contracts/margin/external/ERC721/ERC721MarginPosition.sol
  contracts/margin/external/PayableMarginMinter.sol
  contracts/margin/external/SharedLoan.sol
  contracts/margin/external/SharedLoanFactory.sol
  contracts/margin/external/exchangewrappers/OpenDirectlyExchangeWrapper.sol
  contracts/margin/external/exchangewrappers/ZeroExExchangeWrapper.sol
  contracts/margin/external/payoutrecipients/DutchAuctionCloser.sol
  contracts/margin/impl/BorrowShared.sol
  contracts/margin/impl/ClosePositionImpl.sol
  contracts/margin/impl/ClosePositionShared.sol
  contracts/margin/impl/CloseWithoutCounterpartyImpl.sol
  contracts/margin/impl/DepositCollateralImpl.sol
  contracts/margin/impl/ForceRecoverCollateralImpl.sol
  contracts/margin/impl/IncreasePositionImpl.sol
  contracts/margin/impl/InterestImpl.sol
  contracts/margin/impl/LoanImpl.sol
  contracts/margin/impl/MarginAdmin.sol
  contracts/margin/impl/MarginCommon.sol
  contracts/margin/impl/OpenPositionImpl.sol
  contracts/margin/impl/PositionGetters.sol
  contracts/margin/impl/TransferInternal.sol
  contracts/testing/OmiseToken.sol
  contracts/testing/OwnedToken.sol
  contracts/testing/TestExponent.sol
  contracts/testing/TestLoanOwner.sol
  contracts/testing/TestPositionOwner.sol
  contracts/testing/TestSmartContractLender.sol
  contracts/testing/TestToken.sol
  package-lock.json
  package.json
Labels: task

#423 Add position balances to seeds
  contracts/margin/external/payoutrecipients/DutchAuctionCloser.sol
  migrations/3_seeds.js
  package-lock.json
  package.json
Labels: enhancement, js

#425 Add ERC20PositionWithdrawer
  contracts/margin/external/ERC20/ERC20CappedLong.sol
  contracts/margin/external/ERC20/ERC20CappedShort.sol
  contracts/margin/external/ERC20/ERC20Long.sol
  contracts/margin/external/ERC20/ERC20LongFactory.sol
  contracts/margin/external/ERC20/ERC20Position.sol
  contracts/margin/external/ERC20/ERC20PositionFactory.sol
  contracts/margin/external/ERC20/ERC20PositionWithdrawer.sol
  contracts/margin/external/ERC20/ERC20Short.sol
  contracts/margin/external/ERC20/ERC20ShortFactory.sol
  contracts/margin/external/exchangewrappers/OpenDirectlyExchangeWrapper.sol
  contracts/margin/external/exchangewrappers/ZeroExExchangeWrapper.sol
  contracts/margin/interfaces/ExchangeWrapper.sol
  contracts/testing/TestExchangeWrapper.sol
  migrations/2_deploy.js
  test/tests/margin/TestCloseWithoutCounterparty.js
  test/tests/margin/external/erc20/ERC20PositionHelper.js
  test/tests/margin/external/erc20/TestERC20CappedPosition.js
  test/tests/margin/external/erc20/TestERC20Long.js
  test/tests/margin/external/erc20/TestERC20PositionFactory.js
  test/tests/margin/external/erc20/TestERC20PositionWithdrawer.js
  test/tests/margin/external/erc20/TestERC20Short.js
  test/tests/margin/external/erc20/TestPayableMarginMinter.js
  test/tests/margin/external/erc721/TestERC721MarginLoan.js
  test/tests/margin/external/erc721/TestERC721MarginPosition.js
  test/tests/margin/external/exchangewrappers/TestOpenDirectlyExchangeWrapper.js
  test/tests/margin/external/exchangewrappers/TestZeroExExchangeWrapper.js
  util/DeployGasCosts.js
Labels: Requires Client Changes, enhancement

#429 fix typo in seeds
  package-lock.json
  package.json
  src/lib/seeds.js
Labels: bug, js

#434 Add manual mining functions to docker container
  package-lock.json
  package.json
  src/lib/snapshots.js
Labels: js
