Repository dydxprotocol/protocol, pull requests merged in 2018-09, with the labels that each got.

#436 Rename ZeroEx to V1
  README.md
  contracts/external/0x/v1/README.md
  contracts/external/0x/v1/ZeroExExchangeInterfaceV1.sol
  contracts/external/0x/v1/ZeroExExchangeV1.sol
  contracts/external/0x/v1/ZeroExProxyV1.sol
  contracts/external/0x/v1/base/ZeroExOwnable.sol
  contracts/external/0x/v1/base/ZeroExSafeMath.sol
  contracts/external/0x/v1/base/ZeroExToken.sol
  contracts/margin/Vault.sol
  contracts/margin/external/BucketLender/BucketLender.sol
  contracts/margin/external/exchangewrappers/OpenDirectlyExchangeWrapper.sol
  contracts/margin/external/exchangewrappers/ZeroExV1ExchangeWrapper.sol
  migrations/2_deploy.js
  migrations/deployed.json
  migrations/deployments.md
  src/lib/contracts.js
  test/helpers/ERC20PositionHelper.js
  test/helpers/MarginHelper.js
  test/helpers/ZeroExHelper.js
  test/tests/js/TestSeeds.js
  test/tests/margin/TestIncreasePosition.js
  test/tests/margin/TestInvalidPositions.js
  test/tests/margin/TestOpenPosition.js
  test/tests/margin/external/TestAuctionProxy.js
  test/tests/margin/external/TestWethPayoutRecipient.js
  test/tests/margin/external/erc20/TestPayableMarginMinter.js
  test/tests/margin/external/exchangewrappers/TestZeroExV1ExchangeWrapper.js
Labels: Code Clarity

#437 0.2.15
  migrations/deployed.json
  truffle.js
  util/DeployGasCosts.js
Labels: task

#446 Finalize ProductionERC20Token
  contracts/margin/external/ERC20/ERC20CappedLong.sol
  contracts/margin/external/ERC20/ERC20CappedPosition.sol
  contracts/margin/external/ERC20/ERC20CappedShort.sol
  contracts/margin/external/ERC20/ERC20Position.sol
  contracts/margin/external/payoutrecipients/DutchAuctionCloser.sol
  test/tests/margin/external/TestDutchAuctionCloser.js
  test/tests/margin/external/erc20/TestERC20CappedPosition.js
Labels: Requires Client Changes, second layer

#448 add BucketLenderWithRecoveryDelay
  contracts/margin/external/BucketLender/BucketLender.sol
  contracts/margin/external/BucketLender/BucketLenderWithRecoveryDelay.sol
  test/tests/margin/external/bucketlender/TestBucketLenderWithRecoveryDelay.js
Labels: Requires Client Changes, second layer

#452 add new contracts to `contracts.js`
  package-lock.json
  package.json
  src/lib/contracts.js
Labels: task

#454 Add deploy for mainnet
  truffle.js
Labels: task

#455 Prepare for mainnet deploy
  migrations/2_deploy.js
  package.json
  scripts/save-deployed-addresses.js
Labels: task

#456 Allow callTimeLimit of zero
  contracts/margin/external/payoutrecipients/DutchAuctionCloser.sol
  contracts/margin/impl/MarginCommon.sol
  test/tests/margin/TestOpenPosition.js
  test/tests/margin/TestOpenWithoutCounterparty.js
  test/tests/margin/external/TestDutchAuctionCloser.js
Labels: enhancement
